### ISSUE TITLE
2.1.0 breaks "drag" in jquery-simulate

### ISSUE THREAD

**Issue by YoranBrondsema** [ember-cli/ember-cli-qunit#124]
The changes from https://github.com/ember-cli/ember-cli-qunit/pull/120 break the computation of target positions when simulating dragging of elements in [jquery-simulate](https://github.com/jquery/jquery-simulate). It's because of the `zoom: 50%` was replaced with a CSS scale transform.

Because of this, all pixel values for positions inside the testing container are multiplied by 2. I don't think this is a problem when all position computations happen from within the container. However, it does bring problems when positions are computed at a global `document` level: outside of the container distances are normal but inside the container they are all multiplied by 2.

In this case, I could solve it by dividing the drag distance by 2. However, we are going to stick to 2.0.x instead as we don't want to think about dividing distances by 2 every time we do position computations.

Just out of curiosity, why was the 50% zoom introduced anyway? What was wrong with keeping the normal 100% zoom level?

**Comment by trentmwillis** [comment]
I believe this is due to the same discrepancies brought up in #48. Meaning `zoom` results in different bounding rect values from those produced when using `scale`.

That said, to answer your actual question, I wasn't around when the zoom was introduced, but my feeling is that it is there so that you can view the test runner and container at the same time. Theoretically you could keep the container the same size and still have a normal scaling but that would probably cause the visual representation of the app to not be the same.

**Comment by YoranBrondsema** [comment]
Cool, thanks for answering. That makes sense.

Since no one else seems to have this issue, I'll close it.
