### ISSUE TITLE
Unable to run tests on production build

### ISSUE THREAD

**Issue by joukevandermaas** [ember-cli/ember-cli-qunit#169]
When running the following command in ember-cli 2.10:

```
ember test --environment=production
```

I get the following error:

```
Global error: Uncaught TypeError: Cannot read property 'Adapter' of undefined
```

Inspection shows that `undefined` in this case is `Ember.Test`, which apparently does not exist in production builds. `git bisect` shows that this error was introduced in b26ca0a02b0c94b8555f1732399c485b32c75604.

**Comment by rwjblue** [comment]
What version of ember-cli?

**Comment by rwjblue** [comment]
Can you provide a reproduction repo?

**Comment by Turbo87** [comment]
@rwjblue he tested it with Ember CLI 2.10 (see https://embercommunity.slack.com/archives/-testing/p1484818801003794 and the following messages)

**Comment by joukevandermaas** [comment]
Reproduction repo: https://github.com/joukevandermaas/embertestnotdefined

This is just `ember new` with `ember g acceptance-test dummy`.

**Comment by trentmwillis** [comment]
I looked into this and it appears this also occurs when using ember-cli-mocha. With the new version of QUnit we now are defining a custom test adapter outside the one that Ember normally provides; ember-mocha does the same thing. So, the issue seems to be that `Ember.Test.Adapter` just isn't present in production test builds. Seems that this likely needs to be fixed at either the Ember-CLI or Ember.js level, unsure which though.

**Comment by rwjblue** [comment]
I believe this is fixed upstream in Ember.  Can you confirm?

Going to close for now...

**Comment by joukevandermaas** [comment]
Verified this works with Ember (CLI) 3.0. Same steps:

```
ember new tests-in-prod
cd tests-in-prod
ember g acceptance-test dummy
ember test --environment=production
```
