### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by panthony** [ember-cli/ember-cli-qunit#174]
Using ember 2.10, I bumped the `ember-cli-qunit` to the latest version (`3.1.2`).

After the upgrade I started to have this error on async tests (based on a promise result) that were not returning the promise:

![capture d ecran 2017-03-14 a 15 13 17](https://cloud.githubusercontent.com/assets/230462/23904745/45a0be1e-08c9-11e7-94e9-ca190a58bd5c.png)

Ex:

```javascript
test('it fails with maximum call stack exceeded', function(assert) {
  this.subject().iReturnAPromise()
     .then(() => {
         assert.ok(true);
     });
});

test('it works', function(assert) {
  return this.subject().iReturnAPromise()
     .then(() => {
         assert.ok(true);
     });
});
```

Downgrading to `ember-cli-qunit@2.2.5` fixes the issue.

I agree that the proper way is to return the promise nonetheless the maximum stack size exceeded shouldn't happen.

**Comment by trentmwillis** [comment]
@panthony thanks for reporting. This is related to https://github.com/emberjs/ember-qunit/pull/255 and https://github.com/qunitjs/qunit/issues/1119, which should be fixed by https://github.com/qunitjs/qunit/pull/1120.

I'll leave this issue open to track from this end, but there is likely no work to be done in this repo.

**Comment by trentmwillis** [comment]
Upstream fix has been merged + released. Closing this.
